### ISSUE TITLE
Q1 - L4 Content Priorities

### ISSUE THREAD

**Issue by adams0619** [ibm-build-lab/VAD-VAR-Workshop#282]
Given the ask for L4 content, this is an epic encompassing our list of priorities for Q1... this list will be updated as needed.

- [ ] Retrieval Augmented Generation (RAG) with the most common LLMs (_llama-2_ & _granite_) as well as instruction-following LLMs
  -  [ ] Using VectorDB
  -  [ ] watsonx Discovery
  -  [ ] Watson Discovery
- [ ] Moderate to Advanced Prompt engineering of the LLM 
  - [ ] Within the watsonx.ai Prompt Lab

- [ ] Speech-to-text _on top of RAG_
- [ ] Text-to-Speech _on top of RAG_.

- [ ] Document Classification (Watson Discovery)
